version: '2'

services:
  mongodb:
    image: mongo:latest
    container_name: meseeks_mongodb
    tty: true
    ports:
      - 27018:27018
    command: mongod --smallfiles # --quiet

  golang:
    build: 
      context: .
      dockerfile: ./Docker/dev/golang/dockerfile
    container_name: meseeks_golang
    ports:
     - 3000:3000
    volumes:
     - ./:/go/src/github.com/melzareix/MrMeseeksBot
    working_dir: /go/src/github.com/melzareix/MrMeseeksBot
    depends_on:
      - mongodb
    command: "fresh"