version: '2'

services:
  mongodb:
    image: mongo:latest
    container_name: meseeks_mongodb
    tty: true
    ports:
      - 27017:27017
    command: mongod --smallfiles # --quiet

  golang:
    build: 
      context: .
      dockerfile: ./Docker/dev/golang/Dockerfile
    container_name: meseeks_golang
    ports:
     - 3000:3000
    volumes:
     - ./:/go/src/github.com/melzareix/Backend/MrMeeseeksBot
    working_dir: /go/src/github.com/melzareix/Backend/MrMeeseeksBot
    depends_on:
      - mongodb
    command: "fresh"